services:
  postgres:
    container_name: serhio-payday-postgres
    restart: always
    ports:
      - "5432:5432"

    env_file: ./env_params/.env.postgres.dev

    image: postgres:18.4

    volumes:
      - ./postgresql/scripts:/docker-entrypoint-initdb.d
      - ./postgresql/data:/var/lib/postgresql
    networks:
      - serhio-payday-network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  centrifugo:
    container_name: serhio-payday-centrifugo
    build:
      context: ./centrifugo
      dockerfile: dockerfile.dev
    env_file: ./env_params/.env.centrifugo.dev
    volumes:
      - ./centrifugo/config.dev.json:/centrifugo/config.json
    command: centrifugo -c config.json
    ports:
      - 7000:8000
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    networks:
      - serhio-payday-network 

networks:
  serhio-payday-network:
    name: serhio-payday-network
    driver: bridge