FROM centrifugo/centrifugo:v6.9


ENV TZ=Europe/Moscow

# Устанавливаем рабочую директорию
WORKDIR /centrifugo

# Копируем конфигурационный файл
COPY config.dev.json ./config.dev.json



# Запускаем Centrifugo с указанной конфигурацией
CMD ["centrifugo", "--config", "config.dev.json"]

# Открываем порт 7000
EXPOSE 7000